name: Bug report
description: File a bug report or issue.
title: "[BUG] <concise description>"
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: "### Thanks for taking the time to fill out this bug report!"
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      placeholder: Tell us what happens!
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      render: markdown
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: 1.0.2
    validations:
      required: true
